
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/graphql
    username: root
    password: rootroot
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  graphql:
    jpa:
      query:
        name: GraphQLJpaQueryStarwars
        description: GraphQL Jpa Query Starwars Schema Example
        enabled: true

server:
  port: 10626

logging:
  level:
    root: debug
